{"uuid": "cd1cb8fb-69c4-4f5e-9d9e-3eb993c8227d", "children": ["a81bf989-690f-4451-a359-73537c8be1b2"], "befores": [{"name": "get_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: permission denied\n\n", "trace": "  File \"C:\\Users\\tolos\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\tolos\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\_pytest\\fixtures.py\", line 957, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\tolos\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\_pytest\\fixtures.py\", line 783, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\tolos\\Documents\\GitHub\\CH_096_TAQC\\Tests\\conftest.py\", line 13, in get_driver\n    driver = Driver(Config.BROWSER).set_browser()\n  File \"C:\\Users\\tolos\\Documents\\GitHub\\CH_096_TAQC\\Driver\\driver.py\", line 24, in set_browser\n    return webdriver.Firefox(executable_path=GeckoDriverManager().install())\n  File \"C:\\Users\\tolos\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 174, in __init__\n    keep_alive=True)\n  File \"C:\\Users\\tolos\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\tolos\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 252, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Users\\tolos\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\tolos\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1577192636055, "stop": 1577192645784}], "start": 1577192636055, "stop": 1577192645865}